name: Refresh
on:
  schedule:
    - cron:  '30 9 1 * *'
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: cd scripts && npm i && cd ..
      - run: node scripts/refresh.js
      - name: Commit & Push
        uses: actions-x/commit@v2
        with:
          email: noreply@rrainn.com
          name: GitHub Actions
          branch: master
